### ISSUE TITLE
Page 144 Example 7.8

### ISSUE THREAD

**Issue by juanjo-two** [cryptobook/Errata#1]
Page 144 Example 7.8. For Sagemath 9 and python 3. You can use binascii.unhexlify() to convert from hex string to binary data. The modified lines are:
import binascii
h1 = hashlib.sha1();h1.update(binascii.unhexlify(prefix+m1))
h2 = hashlib.sha1();h2.update(binascii.unhexlify(prefix+m2))
...
h1 = hashlib.sha1();h1.update(binascii.unhexlify(prefix+m1+m))
h2 = hashlib.sha1();h2.update(binascii.unhexlify(prefix+m2+m))

**Comment by cryptobook** [comment]
That's right, thank you! The code for SageMath 9 and Python 3 is available under https://github.com/cryptobook/sagemath-code and I also updated the errata list.
